version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Change to a secure password
      MYSQL_DATABASE: insurance_db       # Name of your database
      MYSQL_USER: user                   # Change to your desired username
      MYSQL_PASSWORD: userpassword       # Change to your desired password
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer_container
    ports:
      - "8080:8080"  # Adminer available at http://localhost:8080

  metabase:
    image: metabase/metabase:latest
    container_name: metabase_container
    ports:
      - "3000:3000"  # Metabase available at http://localhost:3000
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - metabase_data:/metabase-data

volumes:
  mysql_data:
  metabase_data: